# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0004_auto_20170517_1211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
