# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170511_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='news.PostCategory', verbose_name='Категория'),
        ),
    ]
