# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170511_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
