# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('number_phone', models.CharField(max_length=15, unique=True)),
                ('client_message', models.TextField(blank=True)),
            ],
        ),
    ]
