# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170406_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Размер'),
        ),
    ]
