# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(-3, 'S'), (-3, 'M'), (-2, 'L')], verbose_name='Размер'),
        ),
    ]
