# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170504_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(-3, 'S'), (-3, 'M'), (-2, 'L')], default=0, verbose_name='Размер'),
        ),
    ]
