# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170511_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[('', '-------'), (-3, 'S'), (-3, 'M'), (-2, 'L')], default=0, verbose_name='Размер'),
        ),
    ]
