# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170518_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Новый'),
        ),
        migrations.AddField(
            model_name='product',
            name='recomendation',
            field=models.BooleanField(default=False, verbose_name='Рекомендуем'),
        ),
    ]
