# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorites_products',
        ),
    ]
