# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170525_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.AddField(
            model_name='product',
            name='akcii',
            field=models.BooleanField(default=False, verbose_name='Акции'),
        ),
    ]
