# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20170611_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Undercategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undercategory', to='catalog.Category', verbose_name='Категория')),
            ],
        ),
    ]
