# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_commenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenter',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='commenter',
            old_name='user_id',
            new_name='user',
        ),
    ]
