# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20170531_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderauthuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_auth_user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_auth_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrderAuthUser',
        ),
    ]
