# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20170531_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[(1, 'Курьерская доставка или доставка Почтой России ')], default='', max_length=250, verbose_name='Метод'),
        ),
    ]
